;; This "manifest" file can be passed to 'guix package -m' to reproduce
;; the content of your profile.  This is "symbolic": it only specifies
;; package names.  To reproduce the exact same profile, you also need to
;; capture the channels being used, as returned by "guix describe".
;; See the "Replicating Guix" section in the manual.

(specifications->manifest
  (list "tlp"
        "engstrand-dwm"
        "kdeconnect"
        "dunst"
        "sxiv"
        "xwallpaper"
        "xf86-video-fbdev"
        "xf86-input-libinput"
        "xorg-server"
        "xinit"
        "unicode-emoji"
        "font-awesome"
        "font-jetbrains-mono"
        "xprop"
        "curl"
        "redshift"
        "brightnessctl"
        "engstrand-dsblocks"
        "stow"
        "xrandr"
        "xsetroot"
        "pamixer"
        "mpc"
        "xrdb"
        "engstrand-st"
        "harfbuzz"
        "fzf"
        "xstow"
        "bat"
        "xmodmap"
        "xcape"
        "ncurses"
        "picom"
        "fontconfig"
        "xset"
        "xkeyboard-config"
        "pkg-config"
        "glib-networking"
        "libmpdclient"
        "mpd"
        "libxinerama"
        "freetype"
        "libxft"
        "libx11"
        "gcc-toolchain@10"
        "make"
        "node"
        "neovim"
        "vim"
        "git"
        "firefox"
        "openssh"))
