# Export 'SHELL' to child processes.  Programs such as 'screen'
# honor it and otherwise use /bin/sh.
export SHELL

# Source the system-wide file.
source /etc/bashrc

# Source aliases.
[ -f "$HOME/.aliasrc" ] && . "$HOME/.aliasrc"

if [[ $- != *i* ]]
then
    # We are being invoked from a non-interactive shell.  If this
    # is an SSH session (as in "ssh host command"), source
    # /etc/profile so we get PATH and other essential variables.
    [[ -n "$SSH_CLIENT" ]] && source /etc/profile

    # Don't do anything else.
    return
fi

export PASTEL_COLOR_MODE=8bit
PS1="\[$(tput bold)\]\[$(tput setaf 1)\][\[$(tput setaf 3)\]\u\[$(tput setaf 2)\]@\[$(tput setaf 4)\]\h \[$(tput setaf 5)\]\W\[$(tput setaf 1)\]]\[$(tput setaf 7)\]\\$ \[$(tput sgr0)\]"

# Infinite history
HISTSIZE= HISTFILESIZE=

#Allows you to cd into directory merely by typing the directory name.
shopt -s autocd

# Disable ctrl-s and ctrl-q.
stty -ixon

PROMPT_COMMAND='echo -ne "\033]0;${PWD}\007"'
