#!/bin/sh

# less/man colors
export LESS_TERMCAP_mb="$(printf '%b' '[1;31m')"; a="${a%_}"
export LESS_TERMCAP_md="$(printf '%b' '[1;36m')"; a="${a%_}"
export LESS_TERMCAP_me="$(printf '%b' '[0m')"; a="${a%_}"
export LESS_TERMCAP_so="$(printf '%b' '[01;44;33m')"; a="${a%_}"
export LESS_TERMCAP_se="$(printf '%b' '[0m')"; a="${a%_}"
export LESS_TERMCAP_us="$(printf '%b' '[1;32m')"; a="${a%_}"
export LESS_TERMCAP_ue="$(printf '%b' '[0m')"; a="${a%_}"

# less: raw control characters, mouse scrolling
export LESS="-R --mouse --wheel-lines=1"
export KEYTIMEOUT=1

export npm_config_prefix=~/.node_modules

# dmenupass does not exist atm
# export SUDO_ASKPASS="$HOME/.local/bin/tools/dmenupass"
export FZF_DEFAULT_OPTS="-m --height 25% --layout=reverse --color fg:7,bg:-1,hl:1,fg+:232,bg+:6,hl+:255,info:7,prompt:2,spinner:1,pointer:232,marker:1,border:3"

# Export guix configuration
export GUIX_PROFILE="$HOME/.guix-profile"
. "$GUIX_PROFILE/etc/profile"

# Source the nix profile and fonts.
if [ -f /run/current-system/profile/etc/profile.d/nix.sh ]; then
    . /run/current-system/profile/etc/profile.d/nix.sh
    export FONTCONFIG_PATH="$(guix build fontconfig)/etc/fonts"

    # Some applications require this path instead
    # export FONTCONFIG_PATH="$GUIX_PROFILE/share/fonts"
fi
